name=DFRobot_C4004
version=1.0.0
author=DFRobot
maintainer=JiaLi <jia.li@dfrobot.com>
sentence=Arduino library for DFRobot C4004 (SKU:SEN0753).
paragraph=DFRobot_C4004 supports UART frame communication, presence detection, trajectory tracking, tag zones, detection range settings and people counting.
category=Sensors
url=https://github.com/DFRobot/DFRobot_C4004
architectures=*
